name: Build Release

on:
  push:
    tags:
      - v**

jobs:
  build-extension:
    uses: ./.github/workflows/ci-ext.yml

  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [build-extension]

    steps:
      - name: Download Linux release
        uses: actions/download-artifact@v4
        with:
          name: sendvaredit_Linux
          path: sendvaredit_linux

      - name: Download Windows release
        uses: actions/download-artifact@v4
        with:
          name: sendvaredit_Windows
          path: sendvaredit_windows

      - name: Prepare archives
        run: |
          cd sendvaredit_linux
          tar -czf sendvaredit_linux.tar.gz *
          cd ../sendvaredit_windows
          zip -r sendvaredit_windows.zip .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: ${{ github.event.head_commit.message }}
          files: |
            sendvaredit_linux/sendvaredit_linux.tar.gz
            sendvaredit_windows/sendvaredit_windows.zip
